### PR TITLE
Add release workflow to build and publish image.

### PR DESCRIPTION
**Pull request by kishen-v**
- Changes to build and publish image to GitHub container registry.
- Point to ghcr.io for daemonset mode of deployment.

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish can you please check why tide is not merging the PR here?

**Comment by Rajalakshmi-Girish** [comment]
> @Rajalakshmi-Girish can you please check why tide is not merging the PR here?

```
{"branch":"main","component":"tide","controller":"status-update","file":"k8s.io/test-infra/prow/tide/status.go:285","func":"k8s.io/test-infra/prow/tide.(*statusController).expectedStatus","level":"debug","msg":"The PR is not mergeable","org":"ppc64le-cloud","pr":4,"reason":"Merge type \"merge\" disallowed by repo settings","repo":"kube-sentry","severity":"debug","sha":"b80279d473d1c1a6d6d9dd6613d126f67f87cdbd","time":"2023-10-16T05:19:45Z"}
```
looking into.

**Review by mkumatag — APPROVED** [review]

**Comment by mkumatag** [comment]
> > @Rajalakshmi-Girish can you please check why tide is not merging the PR here?
> 
> ```
> {"branch":"main","component":"tide","controller":"status-update","file":"k8s.io/test-infra/prow/tide/status.go:285","func":"k8s.io/test-infra/prow/tide.(*statusController).expectedStatus","level":"debug","msg":"The PR is not mergeable","org":"ppc64le-cloud","pr":4,"reason":"Merge type \"merge\" disallowed by repo settings","repo":"kube-sentry","severity":"debug","sha":"b80279d473d1c1a6d6d9dd6613d126f67f87cdbd","time":"2023-10-16T05:19:45Z"}
> ```
> 
> looking into.

bot account didn't had access to this repo, fixed and see at least now it is adding the labels.

**Comment by Rajalakshmi-Girish** [comment]
> /reopen

Now, known issue with merge of PR containing changes to `.github/workflows`

```
{"base-sha":"0822fc46f1149ac19805d3335008d7ff7a8c31ec","branch":"main","component":"tide","controller":"sync","error":"status code 404 not one of [200 405 409], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/pulls/pulls#merge-a-pull-request\"}","file":"k8s.io/test-infra/prow/tide/github.go:275","func":"k8s.io/test-infra/prow/tide.(*GitHubProvider).mergePRs","level":"debug","merge-targets":[4],"msg":"Merge failed.","org":"ppc64le-cloud","pr":4,"repo":"kube-sentry","severity":"debug","sha":"b80279d473d1c1a6d6d9dd6613d126f67f87cdbd","time":"2023-10-19T09:42:05Z"}
```
ref: https://kubernetes.slack.com/archives/CDECRSC5U/p1667223444882849

@mkumatag Hope the github token has `workflow` permissions.

**Comment by mkumatag** [comment]
> > /reopen
> 
> Now, known issue with merge of PR containing changes to `.github/workflows`
> 
> ```
> {"base-sha":"0822fc46f1149ac19805d3335008d7ff7a8c31ec","branch":"main","component":"tide","controller":"sync","error":"status code 404 not one of [200 405 409], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/pulls/pulls#merge-a-pull-request\"}","file":"k8s.io/test-infra/prow/tide/github.go:275","func":"k8s.io/test-infra/prow/tide.(*GitHubProvider).mergePRs","level":"debug","merge-targets":[4],"msg":"Merge failed.","org":"ppc64le-cloud","pr":4,"repo":"kube-sentry","severity":"debug","sha":"b80279d473d1c1a6d6d9dd6613d126f67f87cdbd","time":"2023-10-19T09:42:05Z"}
> ```
> 
> ref: https://kubernetes.slack.com/archives/CDECRSC5U/p1667223444882849
> 
> @mkumatag Hope the github token has `workflow` permissions.

lemme check, need to fix this!

**Pull request merged**
